version: '3'

services:
  fhir:
    depends_on:
      - mongo
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BULK_BASE_URL: http://localhost:3000
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: bulk-export-server
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EXPORT_WORKERS: 2
    ports:
      - '3000:3000'
    command: npm start

  mongo:
    image: mongo:6.0
    # uncomment the following to have access to the containerized mongo at 27018
    # ports:
    #   - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis

volumes:
  mongo_data:
