version: '3'

services:
  fhir:
    depends_on:
      - mongo
      - redis
    environment:
      # Change this to the public location of bulk-export-server. This should be the FQDN and location of where the
      # bulk-export container is made public to users. ex. https://abacus.example.com/bulk-export
      BULK_BASE_URL: http://localhost:3000
      DB_HOST: mongo
      DB_NAME: bulk-export-server
      REDIS_HOST: redis
      EXPORT_WORKERS: 2
    ports:
      - '3000:3000'

  mongo:
    image: mongo:6.0
    ports:
      - '27017'
    # uncomment the following to have access to the containerized mongo at 27018
    # ports:
    #   - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mongo_data:
